version: "3"

services:
  install:
    image: wodby/node:$NODE_TAG
    working_dir: /home/node/app
    user: root
    environment:
      - NPM_CONFIG_PREFIX=/home/node/app/.npm-global
    volumes:
      - $FRONT_DIR:/home/node/app
    command: npm i --force --no-optional

  build:
    image: wodby/node:$NODE_TAG
    working_dir: /home/node/app
    user: root
    environment:
      - NPM_CONFIG_PREFIX=/home/node/app/.npm-global
    volumes:
      - $FRONT_DIR:/home/node/app
    command: npm run build

  lint:
    image: wodby/node:$NODE_TAG
    working_dir: /home/node/app
    user: root
    environment:
      - NPM_CONFIG_PREFIX=/home/node/app/.npm-global
    volumes:
      - $FRONT_DIR:/home/node/app
    command: npm run lint
